In [2]:
import numpy as np

In [29]:
###Broadcasting The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. 
###Arithmetic operations on arrays are usually done on corresponding elements.
##If two arrays are of exactly the same shape, then these operations are smoothly performed. 
##If the dimensions of two arrays are dissimilar, element-to-element operations are not possible.
##However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. 
###The smaller array is broadcast to the size of the larger array so that they have compatible shapes.###

SyntaxError: invalid syntax (918799382.py, line 2)

In [4]:
# === Broadcasting ===

# Example 1: Scalar + array
arr1 = np.array([1, 2, 3])
print("\narr1 + 10:", arr1 + 10)


arr1 + 10: [11 12 13]


In [5]:
# Example 2: 2D + 1D (row-wise broadcasting)
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([10, 20, 30])
print("\nA + B:\n", A + B)


A + B:
 [[11 22 33]
 [14 25 36]]


In [6]:
# Example 3: 2D + 2D (column-wise broadcasting)
C = np.array([[10],
              [20]])
print("\nA + C:\n", A + C)


A + C:
 [[11 12 13]
 [24 25 26]]


In [7]:

# Example 4: Incompatible shapes (will throw error if uncommented)
try:
    D = np.array([100, 200])
    print("\nA + D:\n", A + D)
except ValueError as e:
    print("\nA + D: Broadcasting Error:", e)


A + D: Broadcasting Error: operands could not be broadcast together with shapes (2,3) (2,) 


In [8]:
# If they are of different dimensions 
D=np.arange(4) 
E=np.arange(20).reshape(5,4) 
print(D) 
print(E)

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [9]:
#If x-m and yen, operation will take place 
a1=np.arange(8).reshape(2,4) 
a2=np.arange(8,16).reshape (2,4) 
a1 + a2 


array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [11]:
#Tf x=1 and yen then also operation will take place (Same Dimension) 
a3=np.arange(3).reshape(1,3) 
a4=np.arange(12).reshape(4,3) 
print(a3,a4)

[[0 1 2]] [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [14]:
#if x=1 and y!-n then also operation will not take place Error;;;;;
a5=np.arange(3).reshape(1,3) 
a6=np.arange(16).reshape(4,4) 
print(a5) 
print(a6)

[[0 1 2]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [15]:
print(a5+a6)

ValueError: operands could not be broadcast together with shapes (1,3) (4,4) 

In [17]:
# If x=1 und n=1 then y==m, operution to Luke place 
a7=np.arange(3).reshape(1,3) 
a8=np.arange(3).reshape(3,1) 
print(a7) 
print(a8)

[[0 1 2]]
[[0]
 [1]
 [2]]


In [18]:
print(a7+a8)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [22]:
#If x-1 and y-1, then the operation will take place no matter what 
a9=np.arange(1).reshape(1,1)
a10=np.arange(20).reshape(4,5) 
print(a9) 
print(a10)

[[0]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [23]:
print(a9+a10)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [27]:
# If they are of different dimensions 
a11=np.arange(4) 
a12=np.arange(20).reshape(5,4) 
print(a11) 
print(a12)

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [28]:
print(a11+a12)

[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]
 [12 14 16 18]
 [16 18 20 22]]
