In [1]:
print("Hello World")

Hello World


In [2]:
#Creating Numpy n-d Arrays
import numpy as np
arr1= np.array([1,2,3,4,5,6])

In [8]:
type(arr1)

numpy.ndarray

In [3]:
arr1

array([1, 2, 3, 4, 5, 6])

In [118]:
arr2= np.zeros((2,3))

In [119]:
arr2.itemsize

8

In [120]:
arr3= np.ones((2,3))

In [121]:
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [123]:
arr4=np.identity(5)

In [124]:
arr4.itemsize

8

In [125]:
arr5=np.arange(20)

In [126]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [127]:
arr6=np.arange(11,21)

In [128]:
arr6

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [129]:
arr7=np.arange(11,21,2)

In [131]:
arr7

array([11, 13, 15, 17, 19])

In [132]:
arr8=np.linspace(10,20,10)

In [133]:
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [135]:
arr9=np.copy(arr1)

In [136]:
arr9

array([1, 2, 3, 4, 5, 6])

In [137]:
arr9.dtype

dtype('int64')

In [138]:
arr1=np.array([1,2,3,4,5,6])
arr2= np.zeros((2,3))


In [139]:
arr1.shape

(6,)

In [140]:
arr2.shape

(2, 3)

In [141]:
arr3=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

In [142]:
arr3.shape

(2, 2, 2)

In [143]:
arr3.size

8

In [144]:
arr3.itemsize

8

In [145]:
arr3.ndim

3

In [146]:
arr2.ndim

2

In [147]:
arr1.ndim

1

In [148]:
arr1.size

6

In [149]:
arr1.itemsize

8

In [150]:
arr1.dtype

dtype('int64')

In [151]:
arr3.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[1., 2.],
        [3., 4.]]])

In [152]:
lista=(range(100))

In [70]:
lista

range(0, 100)

In [71]:
arr4=np.arange(0,100)

In [74]:
import sys
print(sys.getsizeof(87)*len(lista))

2800


In [75]:
print(arr4.itemsize*arr4.size)

800


In [109]:
x=range(10000000)
y=range(10000000,20000000)

In [110]:
x

range(0, 10000000)

In [111]:
y

range(10000000, 20000000)

In [112]:
import time
start_time= time.time()

In [113]:
c=[(x,y) for x,y in zip(x,y)]

In [114]:
print(time.time()-start_time)

1.9481956958770752


In [115]:
import time
start_time= time.time()

In [116]:
a=np.arange(10000000)
b=np.arange(10000000,20000000)

c=a+b

In [117]:
print(time.time()-start_time)

0.6759066581726074


In [153]:
arr1

array([1, 2, 3, 4, 5, 6])

In [159]:
arr1[2:4]

array([3, 4])

In [160]:
arr10=np.arange(24).reshape(4,6)

In [161]:
arr10

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [188]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])    # [20 30 40]
print(arr[:3])     # [10 20 30]
print(arr[::2])    # [10 30 50] (step of 2)
print(arr[::-1])   # [50 40 30 20 10] (reversed)

[20 30 40]
[10 20 30]
[10 30 50]
[50 40 30 20 10]


In [195]:
print(arr10[0:2, 0:3])   # Top-left 2x3 matrix)


print(arr10[2:, 3:])     # Bottom-right 2x3 matrix

print(arr10[1:3, 2:5])   # Middle section


[[0 1 2]
 [6 7 8]]
[[15 16 17]
 [21 22 23]]
[[ 8  9 10]
 [14 15 16]]


In [162]:
arr10[2:,4:]

array([[16, 17],
       [22, 23]])

In [187]:
print(arr10[0, 1])  # 2 (row 0, column 1)
print(arr10[1, 2])  # 6 (row 1, column 2)

1
8


In [163]:
for i in np.nditer(arr10):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [164]:
import numpy as np


In [165]:
A = np.array([[10, 20], [30, 40]])
B = np.array([[1, 2], [3, 4]])

In [166]:
print(A - B)          #Element-wise Subtraction


[[ 9 18]
 [27 36]]


In [167]:
print(B ** 2)     # Element-wise Power

[[ 1  4]
 [ 9 16]]


In [168]:
print(A < 35)      #Boolean Comparison

[[ True  True]
 [ True False]]


In [169]:
print(A * B)      #Element-wise Multiplication

[[ 10  40]
 [ 90 160]]


In [170]:
print(A.dot(B))    #Matrix Multiplication

[[ 70 100]
 [150 220]]


In [173]:
print(A.min()) #Minimum Element
print(A.min(axis=0))
print(A.min(axis=1))

10
[10 20]
[10 30]


In [175]:
print(A.max()) #Maximun Element
print(A.max(axis=0))
print(A.max(axis=1))

40
[30 40]
[20 40]


In [179]:
print(A.sum())         #Sum of elements
print(A.sum(axis=0))
print(A.sum(axis=1))

100
[40 60]
[30 70]


In [182]:
print(np.exp(B))   #Exponental

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [183]:
np.sqrt(A)       # Square Root

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

In [184]:
np.sin(A) # Sine Function

array([[-0.54402111,  0.91294525],
       [-0.98803162,  0.74511316]])

In [185]:
arr = np.array([1.5, 2.5, 3.5])
print(arr.astype(int))

[1 2 3]


In [197]:
arr4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 

In [199]:
arr4.ndim

2

In [202]:
arr4.ravel()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [204]:
A.transpose()

array([[10, 30],
       [20, 40]])

In [208]:
print(A)
print(B)

[[10 20]
 [30 40]]
[[1 2]
 [3 4]]


In [216]:
C=np.hstack((A,B))

In [217]:
C

array([[10, 20,  1,  2],
       [30, 40,  3,  4]])

In [209]:
C.ndim

2

In [210]:
D=np.vstack((A,B))

In [211]:
D

array([[10, 20],
       [30, 40],
       [ 1,  2],
       [ 3,  4]])

In [221]:
np.hsplit(C,2)

[array([[10, 20],
        [30, 40]]),
 array([[1, 2],
        [3, 4]])]

In [215]:
np.vsplit(D,2)

[array([[10, 20],
        [30, 40]]),
 array([[1, 2],
        [3, 4]])]

In [223]:
arr13= np.arange(24).reshape(6,4)
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [225]:
arr13[[2,4,5]]     #Fancy Indexing

array([[ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [226]:
arr14= np.random.randint(low=10,high=100,size=20).reshape(4,5)

In [227]:
arr14

array([[92, 65, 20, 31, 87],
       [73, 33, 39, 65, 96],
       [12, 72, 26, 73, 76],
       [29, 76, 72, 66, 60]], dtype=int32)

In [230]:
arr14[arr14>50]

array([92, 65, 87, 73, 65, 96, 72, 73, 76, 76, 72, 66, 60], dtype=int32)

In [232]:
arr14[(arr14>70) & (arr14 !=0)]

array([92, 87, 73, 96, 72, 73, 76, 76, 72], dtype=int32)

In [233]:
arr14[(arr14>70) & (arr14 !=0)]=0

In [234]:
arr14

array([[ 0, 65, 20, 31,  0],
       [ 0, 33, 39, 65,  0],
       [12,  0, 26,  0,  0],
       [29,  0,  0, 66, 60]], dtype=int32)