In [1]:
import numpy as np

In [3]:
np.random.random()

0.004555635983570339

In [4]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [10]:
np.random.uniform(2,4)

2.3725204227553416

In [13]:
np.random.uniform(2,4,10).reshape(2,5)

array([[2.28077388, 2.39620298, 3.60148914, 3.93652315, 2.62684836],
       [3.38464523, 3.7527783 , 3.78921333, 2.17008842, 2.07810957]])

In [24]:
np.random.randint(2,40,15).reshape(3,5)

array([[ 5,  6, 26, 14, 28],
       [18, 20, 17,  2,  6],
       [27, 36, 25,  9, 28]], dtype=int32)

In [31]:
a=np.random.randint(9,39,7)

In [32]:
a

array([17, 31, 18, 12, 16, 32, 38], dtype=int32)

In [33]:
np.max(a)

np.int32(38)

In [34]:
np.min(a)

np.int32(12)

In [35]:
np.argmax(a)

np.int64(6)

In [36]:
np.argmin(a)

np.int64(3)

In [37]:
a=np.random.randint(9,39,7)

In [38]:
a

array([13, 36, 14, 34, 28, 15, 17], dtype=int32)

In [39]:
a[a%2==1]=-1

In [40]:
a

array([-1, 36, 14, 34, 28, -1, -1], dtype=int32)

In [41]:
a=np.random.randint(9,39,7)

In [42]:
a

array([ 9, 11, 19, 32, 24, 24, 32], dtype=int32)

In [46]:
b=np.where(a%2==1,-1,a)
b

array([-1, -1, -1, 32, 24, 24, 32], dtype=int32)

In [47]:
a

array([ 9, 11, 19, 32, 24, 24, 32], dtype=int32)

In [48]:
a=np.random.randint(9,39,10)

In [49]:
a

array([34, 16, 28, 37, 19, 23,  9, 33, 32, 32], dtype=int32)

In [51]:
a=np.sort(a)
a

array([ 9, 16, 19, 23, 28, 32, 32, 33, 34, 37], dtype=int32)

In [53]:
np.percentile(a,50)

np.float64(30.0)